global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8082']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8083']

  - job_name: 'pricing-service'
    static_configs:
      - targets: ['pricing-service:8084']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 